
language: node_js
sudo: false
node_js:
  - "6.2"
  - "5"
  - "4"
cache:
  directories:
    - node_modules

before_install:
  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
install:
  - npm install -g codecov
  - npm install
script:
  - npm run -s jshint
  - travis_retry npm test
after_success:
  - npm run codecov
